nginx_public_ip: "${nginx_public_ip}"
bastion_private_ip: "${bastion_private_ip}"
webserver_private_ip: "${webserver_private_ip}"
control_server_private_ip: "${control_server_private_ip}"
control_server_public_ip: "${control_server_public_ip}"
